In [42]:
A = np.random.randn(10, 128)   # 10个128维向量

norm = np.linalg.norm(A,axis=1,keepdims=True)
Anorm = A / norm

B = Anorm @ Anorm.T
print(np.diag(B))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [41]:
import numpy as np
# 练习一
data = np.random.randn(100, 5)

mean = np.mean(data,axis=0,keepdims=True)
std = np.std(data,axis=0, keepdims=True)
data_normalized = (data - mean) / std

print("各列均值：\n", np.round(data_normalized.mean(axis=0), 10))
print("各列标准差：\n", np.round(data_normalized.std(axis=0), 10))

各列均值：
 [-0.  0. -0.  0.  0.]
各列标准差：
 [1. 1. 1. 1. 1.]


In [43]:
# 练习3：实现 softmax（数值稳定版）
def softmax(x):
    max = np.max(x,axis=-1,keepdims=True)
    demaxval = x-max
    xexp = np.exp(demaxval)
    xsum = np.sum(xexp,axis=-1,keepdims=True)
    xsoftmax = xexp / xsum
    return xsoftmax

In [44]:
import numpy as np
# 练习4：实现 one-hot 编码
def one_hot(labels, num_classes):
    N = len(labels)
    oh = np.zeros((N,num_classes),dtype=np.float32)

    oh[np.arange(N),labels] = 1.0
    # labels: shape (N,)，整数标签
    # 返回: shape (N, num_classes) 的 float32 矩阵
    return oh

In [45]:
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

x1 = np.array([2.0, 1.0, 0.1])
out1 = softmax(x1)
print("一维输入结果：", out1)
print("一维结果总和：", np.sum(out1))

x2 = np.array([[1, 2, 3], [4, 5, 6]])
out2 = softmax(x2)
print("\n二维输入结果：\n", out2)
print("每一行总和：", np.sum(out2, axis=-1))

x_big = np.array([1000, 999])
print("\n超大数输入softmax结果：", softmax(x_big))


一维输入结果： [0.65900114 0.24243297 0.09856589]
一维结果总和： 1.0

二维输入结果：
 [[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]
每一行总和： [1. 1.]

超大数输入softmax结果： [0.73105858 0.26894142]


In [46]:
labels1 = np.array([0, 2, 1, 0])
res1 = one_hot(labels1, num_classes=3)
print("测试结果：\n", res1)

测试结果：
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [47]:
# 练习5：向量化实现 k-NN（最近邻搜索）
def knn_distances(query, database):
    # query: (Q, D)
    # database: (N, D)
    Q, D = query.shape
    N, _ = database.shape

    # 每一个query向量L2平方和 (Q,1)
    q_sq = np.sum(query ** 2, axis=1, keepdims=True)
    # 每一个database向量L2平方和 (1,N)
    d_sq = np.sum(database ** 2, axis=1, keepdims=True).T
    # 点积 (Q,N)
    dot = query @ database.T

    # 欧式距离平方
    dist_sq = q_sq - 2 * dot + d_sq
    # 防止浮点极小负数，截断到0
    dist_sq = np.maximum(dist_sq, 0.0)
    # 开根号得到标准欧式距离
    dist = np.sqrt(dist_sq)

    return dist

In [48]:
if __name__ == "__main__":
    database = np.array([
        [0, 0],
        [3, 4]
    ])
    query = np.array([
        [0, 5]
    ])

    dist_matrix = knn_distances(query, database)
    print("距离矩阵 shape(Q,N) =", dist_matrix.shape)
    print("计算出的距离：\n", dist_matrix)

距离矩阵 shape(Q,N) = (1, 2)
计算出的距离：
 [[5.         3.16227766]]


In [ ]:
小结：机器学习数据处理优先向量化，拒绝多层循环；Jupyter 实验阶段一定要打印 shape、均值、和值做校验，保证逻辑正确后再落地正式代码。