# Week 1 示例：NumPy 向量化练习

- 作者：共享仓库示例
- 日期：2026-07-15
- 来源：《实验室新生暑期居家集训学习计划》Week 1，NumPy 核心
- 适用周次：Week 1
- 分类：NumPy / SciPy
- 关键词：广播、z-score、余弦相似度、softmax、one-hot、向量化 k-NN
- 运行环境：Python 3.10+、NumPy；SciPy 为可选依赖

## 学习目标

1. 用广播完成批量数组运算。
2. 不使用显式 `for` 循环实现几个常见的机器学习基础操作。
3. 为函数增加简单的形状检查和 `assert` 自检。

> 这是从原始学习计划五道 NumPy 练习中抽取的可运行示例，不替代个人完整练习。

### 数组基础
np.array()、
np.zeros()、
np.ones()、
np.eye()、
np.arange()、
np.linspace()，
以及四个属性：
shape、
ndim、
size、
dtype
### 索引、切片和变形
x[0]、
x[:, 1]、
x[1:3, 2:5]、
x[x > 10]、
x[[0, 2]]，
以及：
reshape()、
flatten()、
ravel()、
concatenate()、
vstack()、
hstack()
### axis、keepdims和广播
### 向量化和矩阵乘法
A * B       （对应位置相乘）、
A @ B       （矩阵乘法）、
np.sum()、
np.mean()、
np.linalg.norm()

# 一、数组基础

In [1]:
import numpy as np

print("NumPy 版本：", np.__version__)

# 创建固定随机数生成器，使每次运行结果相同
rng = np.random.default_rng(42)

NumPy 版本： 2.5.1


In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.zeros((3, 4)) #生成3行4列的全零数组，形状是(3,4)
c = np.ones((2, 3), dtype=np.float32)
d = np.eye(4)
e = np.arange(0, 10, 2)  #从0开始，到10之前结束，步长为2
f = np.linspace(0, 1, 5)  #含义是把闭区间 [0, 1] 均匀分成5个点
g = rng.normal(size=(3, 4))

print("a =", a)
print("\nb =\n", b)
print("\nc =\n", c)
print("\nd =\n", d)
print("\ne =", e)
print("\nf =", f)
print("\ng =\n", g)

a = [1 2 3 4 5]

b =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

c =
 [[1. 1. 1.]
 [1. 1. 1.]]

d =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

e = [0 2 4 6 8]

f = [0.   0.25 0.5  0.75 1.  ]

g =
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]]


In [3]:
print("形状 shape：", g.shape)
print("维度数 ndim：", g.ndim)
print("元素总数 size：", g.size)
print("数据类型 dtype：", g.dtype)

形状 shape： (3, 4)
维度数 ndim： 2
元素总数 size： 12
数据类型 dtype： float64


# 二、索引和切片

In [4]:
x = np.arange(24).reshape(4, 6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [5]:
print("第0行：")
print(x[0])

print("\n第2列：")
print(x[:, 2])

print("\n第1到2行、第2到4列：")
print(x[1:3, 2:5])   #左边包含，右边不包含

print("\n所有大于10的元素：")
print(x[x > 10])

print("\n第0行和第2行：")
print(x[[0, 2], :])

第0行：
[0 1 2 3 4 5]

第2列：
[ 2  8 14 20]

第1到2行、第2到4列：
[[ 8  9 10]
 [14 15 16]]

所有大于10的元素：
[11 12 13 14 15 16 17 18 19 20 21 22 23]

第0行和第2行：
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


# 三、理解axis

In [6]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("原数组：")
print(x)

print("\n全部求和：", x.sum())
print("axis=0：", x.sum(axis=0))  #消除第0维，也就是把各行压在一起，得到每列的结果
print("axis=1：", x.sum(axis=1))  #消除第1维，也就是把各列压在一起，得到每行的结果

原数组：
[[1 2 3]
 [4 5 6]]

全部求和： 21
axis=0： [5 7 9]
axis=1： [ 6 15]


In [7]:
x.mean(axis=0)  #表示每一列的均值
x.mean(axis=1)  #表示每一行的均值

array([2., 5.])

# 四、理解keepdims=True

In [8]:
data = rng.normal(size=(4, 3))

mean_without_keepdims = data.mean(axis=1)
mean_with_keepdims = data.mean(axis=1, keepdims=True)

print("data shape：", data.shape)
print("不使用 keepdims：", mean_without_keepdims.shape)
print("使用 keepdims：", mean_with_keepdims.shape) #keepdims=True 表示求均值后仍保留原来的维度位置

data shape： (4, 3)
不使用 keepdims： (4,)
使用 keepdims： (4, 1)


# 五、理解广播机制
广播判断规则：从最右侧维度开始比较。两个维度满足以下任意条件，就可以广播：1，两个维度相等；2，其中一个维度是1；3，某个数组缺少这一维，可以在左侧补1。

a = np.ones((4, 1, 3))
b = np.ones((5, 3))

c = a + b #给 b左侧补1 b：1 × 5 × 3   a：4 × 1 × 3

print(a.shape)
print(b.shape)
print(c.shape) #4 和 1：可以广播,1 和 5：可以广播,3 和 3：相同

# 六、Notebook中五个函数的核心逻辑
## 1，z-score标准化
目标让每一列：均值约为0，标准差约为1.

In [9]:
data = rng.normal(size=(100, 5))

# 请补充
mean = data.mean(axis=0, keepdims=True)
std = data.std(axis=0, keepdims=True)
data_normalized = (data - mean) / std

print(data_normalized.mean(axis=0))
print(data_normalized.std(axis=0))

assert data_normalized.shape == data.shape
assert np.allclose(data_normalized.mean(axis=0), 0)
assert np.allclose(data_normalized.std(axis=0), 1)

[ 2.22044605e-18 -4.66293670e-17 -2.55351296e-17  1.99840144e-17
  1.85962357e-17]
[1. 1. 1. 1. 1.]


## 2,余弦相似度矩阵

In [10]:
A = rng.normal(size=(10, 128)) #表示有10个128维向量。
assert A.shape == (10, 128)
norms = np.linalg.norm(A, axis=1, keepdims=True) #首先计算每个向量的长度
A_normalized = A / norms #然后归一化
similarities = A_normalized @ A_normalized.T #最后矩阵乘法
print(np.diag(similarities))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 3,数值稳定版softmax

In [11]:
exp_x = np.exp(x)
result = exp_x / exp_x.sum(axis=-1, keepdims=True)

当输入很大时可能溢出，因此先减去每行最大值，再计算指数，检查每行概率和

In [12]:
import numpy as np
def softmax(x):
    """对数组最后一个维度计算数值稳定的 softmax。"""
    x = np.asarray(x, dtype=np.float64)
    if x.ndim == 0:
        raise ValueError("x 至少应为一维数组")
    # 每组数据减去该组最大值，避免 exp 溢出
    shifted = x - np.max(x, axis=-1, keepdims=True)
    exp_x = np.exp(shifted)
    result = exp_x / exp_x.sum(axis=-1, keepdims=True)
    # 自检：输出形状不变
    assert result.shape == x.shape
    # 自检：最后一个维度的概率和为1
    assert np.allclose(result.sum(axis=-1), 1)
    return result
# 测试数据：包含较大的数值
x = np.array([
    [1000, 1001, 1002],
    [1, 2, 3],
    [-1000, -999, -998]
])
result = softmax(x)
print("Softmax 结果：")
print(result)
print("\n每行概率之和：")
print(result.sum(axis=-1))

Softmax 结果：
[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]

每行概率之和：
[1. 1. 1.]


## 4，one-hot编码

In [13]:
labels = np.array([0, 2, 1])
num_classes=3
# 创建全零矩阵，形状为：样本数 × 类别数
result = np.zeros(
    (labels.size, num_classes),
    dtype=np.float32
)
result[np.arange(labels.size), labels] = 1
print(result)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


## 5，向量化k-NN距离

In [14]:
Q = 3
N = 5
D = 4
query = rng.normal(size=(Q, D))
database = rng.normal(size=(N, D))
print("query 的形状：", query.shape)
print("database 的形状：", database.shape)
query_expanded = query[:, None, :]          # (Q, 1, D)
database_expanded = database[None, :, :]    # (1, N, D)
print("扩展后 query 的形状：", query_expanded.shape)
print("扩展后 database 的形状：", database_expanded.shape)
# 利用广播计算每个查询向量和每个数据库向量的差
# (Q, 1, D) - (1, N, D) -> (Q, N, D)
differences = query_expanded - database_expanded
# 沿最后一个维度计算平方和
squared = (differences ** 2).sum(axis=-1)
# 开平方，得到欧氏距离矩阵
distances = np.sqrt(squared)
print("\n距离矩阵：")
print(distances)
print("\n距离矩阵形状：", distances.shape)
# 自检
assert query.shape == (Q, D)
assert database.shape == (N, D)
assert distances.shape == (Q, N)
assert np.all(distances >= 0)

query 的形状： (3, 4)
database 的形状： (5, 4)
扩展后 query 的形状： (3, 1, 4)
扩展后 database 的形状： (1, 5, 4)

距离矩阵：
[[2.92194194 3.61218214 3.20250383 1.97116985 2.63366763]
 [3.04357698 4.64560372 4.6175796  3.69655763 3.50661166]
 [1.08381958 2.93338506 2.52088819 1.40476629 1.60703586]]

距离矩阵形状： (3, 5)
